from functools import lru_cache

from langchain_ollama import ChatOllama

from app.config import settings
from app.rag.vectorstore import similarity_search

SYSTEM_PROMPT = """Réponds uniquement à partir du contexte. Si l'information manque, dis-le.
Réponds dans la langue de la question, en une phrase concise. N'ajoute aucune information.

Contexte :
{context}
"""

STOP_SEQUENCES = [
    "\nQuestion", "\nquestion", "\nQuestion :", "\nQuestion:",
    "\nUtilisateur", "\nHuman:", "\nUser:",
]


@lru_cache
def get_llm() -> ChatOllama:
    return ChatOllama(
        base_url=settings.ollama_base_url,
        model=settings.ollama_model,
        temperature=0.2,
        stop=STOP_SEQUENCES,
        num_predict=settings.ollama_num_predict,
        # Keep the model loaded in memory between requests — Ollama's default is to
        # unload after 5 min idle, which adds a 1-3 min reload on the next question.
        keep_alive=settings.ollama_keep_alive,
        # Pin inference to the physical core count (this machine: 6c/12t). On CPU-only
        # llama.cpp inference, hyperthreads rarely speed up matmul-heavy work and can
        # even add scheduling overhead, so num_thread=6 tends to beat the auto default.
        num_thread=6,
        # Shrink the context window to match the now-smaller retrieved context
        # (retrieval_k=2, chunk_size=700) — less state for Ollama to allocate/scan per call.
        num_ctx=2048,
    )


NO_DOCS_ANSWER = (
    "Aucun document pertinent n'a été trouvé pour répondre à cette question. "
    "Veuillez importer des documents ou reformuler votre question."
)


def retrieve_context(question: str, owner_id: int):
    """Retrieval only — fast, no LLM call. Returns (docs, sources) so sources are
    known immediately, before generation even starts."""
    docs = similarity_search(question, owner_id=owner_id, k=settings.retrieval_k)
    sources = [
        {"filename": doc.metadata.get("filename", "inconnu"), "content": doc.page_content[:400]}
        for doc in docs
    ]
    return docs, sources


def answer_question(question: str, owner_id: int) -> dict:
    docs, sources = retrieve_context(question, owner_id=owner_id)

    if not docs:
        return {"answer": NO_DOCS_ANSWER, "sources": []}

    context = "\n\n---\n\n".join(
        f"[Source: {doc.metadata.get('filename', 'inconnu')}]\n{doc.page_content}" for doc in docs
    )

    llm = get_llm()
    messages = [
        ("system", SYSTEM_PROMPT.format(context=context)),
        ("human", question),
    ]
    response = llm.invoke(messages)

    return {"answer": response.content, "sources": sources}


def stream_answer_tokens(question: str, docs: list):
    """Yields answer text chunks as they're generated by the LLM."""
    if not docs:
        yield NO_DOCS_ANSWER
        return

    context = "\n\n---\n\n".join(
        f"[Source: {doc.metadata.get('filename', 'inconnu')}]\n{doc.page_content}" for doc in docs
    )

    llm = get_llm()
    messages = [
        ("system", SYSTEM_PROMPT.format(context=context)),
        ("human", question),
    ]
    for chunk in llm.stream(messages):
        if chunk.content:
            yield chunk.content
