from langchain_ollama import ChatOllama

from app.config import settings
from app.rag.vectorstore import similarity_search

SYSTEM_PROMPT = """Tu es un assistant d'entreprise qui répond aux questions en te basant \
UNIQUEMENT sur le contexte fourni ci-dessous, extrait des documents internes de l'entreprise. \
Si la réponse ne se trouve pas dans le contexte, dis clairement que tu ne disposes pas de \
cette information dans les documents. Ne fabrique pas de réponse. Réponds dans la langue de \
la question. Donne une seule réponse, concise et directe, à la question posée. N'invente \
pas d'autres questions et ne poursuis pas la conversation au-delà de cette unique réponse.

Contexte :
{context}
"""

STOP_SEQUENCES = [
    "\nQuestion", "\nquestion", "\nQuestion :", "\nQuestion:",
    "\nUtilisateur", "\nHuman:", "\nUser:",
]


def get_llm() -> ChatOllama:
    return ChatOllama(
        base_url=settings.ollama_base_url,
        model=settings.ollama_model,
        temperature=0.2,
        stop=STOP_SEQUENCES,
        num_predict=100,
    )


NO_DOCS_ANSWER = (
    "Aucun document pertinent n'a été trouvé pour répondre à cette question. "
    "Veuillez importer des documents ou reformuler votre question."
)


def retrieve_context(question: str, owner_id: int):
    """Retrieval only — fast, no LLM call. Returns (docs, sources) so sources are
    known immediately, before generation even starts."""
    docs = similarity_search(question, owner_id=owner_id, k=settings.retrieval_k)
    sources = [
        {"filename": doc.metadata.get("filename", "inconnu"), "content": doc.page_content[:400]}
        for doc in docs
    ]
    return docs, sources


def answer_question(question: str, owner_id: int) -> dict:
    docs, sources = retrieve_context(question, owner_id=owner_id)

    if not docs:
        return {"answer": NO_DOCS_ANSWER, "sources": []}

    context = "\n\n---\n\n".join(
        f"[Source: {doc.metadata.get('filename', 'inconnu')}]\n{doc.page_content}" for doc in docs
    )

    llm = get_llm()
    messages = [
        ("system", SYSTEM_PROMPT.format(context=context)),
        ("human", question),
    ]
    response = llm.invoke(messages)

    return {"answer": response.content, "sources": sources}


def stream_answer_tokens(question: str, docs: list):
    """Yields answer text chunks as they're generated by the LLM."""
    if not docs:
        yield NO_DOCS_ANSWER
        return

    context = "\n\n---\n\n".join(
        f"[Source: {doc.metadata.get('filename', 'inconnu')}]\n{doc.page_content}" for doc in docs
    )

    llm = get_llm()
    messages = [
        ("system", SYSTEM_PROMPT.format(context=context)),
        ("human", question),
    ]
    for chunk in llm.stream(messages):
        if chunk.content:
            yield chunk.content
